const USER_BOOKS_QUERY_KEY = "usersBooks";

const FINISHED_READING = "FINISHED_READING";
const PLAN_TO_READ = "PLAN_TO_READ";

const TOAST_ERROR_DEFAULT = "Please try again.";

export {
  USER_BOOKS_QUERY_KEY,
  FINISHED_READING,
  PLAN_TO_READ,
  TOAST_ERROR_DEFAULT,
};
